import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans, Comfortaa } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";

const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" });

const comfortaa = Comfortaa({
    subsets: ["latin"],
    weight: ["300"],
    variable: "--font-comfortaa",
    display: "swap",
});

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={cn(
                "h-full",
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                nunitoSans.variable,
                comfortaa.variable,
                "font-sans"
            )}
        >
            <body className="min-h-full flex flex-col"><TooltipProvider>{children}</TooltipProvider></body>
        </html>
    );
}
